In [1]:
import pandas as pd

In [89]:
df = pd.read_csv("/Users/mac/Desktop/Pandas_Demo/data/survey_results_public.csv", index_col='Respondent')

In [90]:
df

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [4]:
high_salary  = (df['ConvertedComp'] > 70000)

In [5]:
df.sort_values(by=['Country', 'ConvertedComp'], ascending=[True, False], inplace=True)

In [6]:
df[['Country', 'ConvertedComp']].head(50)

                Country  ConvertedComp
Respondent
63129       Afghanistan      1000000.0
50499       Afghanistan       153216.0
39258       Afghanistan        19152.0
58450       Afghanistan        17556.0
7085        Afghanistan        14364.0
22450       Afghanistan         7980.0
48436       Afghanistan         4464.0
10746       Afghanistan         3996.0
8149        Afghanistan         1596.0
29736       Afghanistan         1116.0
722         Afghanistan            0.0
28638       Afghanistan            0.0
6417        Afghanistan            NaN
7353        Afghanistan            NaN
12310       Afghanistan            NaN
26340       Afghanistan            NaN
29045       Afghanistan            NaN
33178       Afghanistan            NaN
37802       Afghanistan            NaN
40000       Afghanistan            NaN
43106       Afghanistan            NaN
44403       Afghanistan            NaN
45854       Afghanistan            NaN
47110       Afghanistan            NaN
49702       Afghanistan            NaN
50767       Afghanistan            NaN
51859       Afghanistan            NaN
58760       Afghanistan            NaN
59560       Afghanistan            NaN
60569       Afghanistan            NaN
60946       Afghanistan            NaN
62168       Afghanistan            NaN
62525       Afghanistan            NaN
74386       Afghanistan            NaN
80926       Afghanistan            NaN
85715       Afghanistan            NaN
85825       Afghanistan            NaN
86362       Afghanistan            NaN
86932       Afghanistan            NaN
87091       Afghanistan            NaN
88582       Afghanistan            NaN
88731       Afghanistan            NaN
2782        Afghanistan            NaN
63019       Afghanistan            NaN
38308           Albania       187668.0
3787            Albania       114550.0
9270            Albania        74474.0
6716            Albania        60000.0
10303           Albania        57300.0
66280           Albania        41244.0

In [7]:
df['ConvertedComp'].nlargest(10)

Respondent
25983    2000000.0
87896    2000000.0
22013    2000000.0
28243    2000000.0
72732    2000000.0
78151    2000000.0
80200    2000000.0
52132    2000000.0
75561    2000000.0
32250    2000000.0
Name: ConvertedComp, dtype: float64

In [8]:
df.nlargest(10, 'ConvertedComp')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
25983,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,...,Just as welcome now as I felt last year,NaN,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
87896,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,32.0,Man,No,Gay or Lesbian,White or of European descent,No,Appropriate in length,Neither easy nor difficult
22013,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy
28243,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot less welcome now than last year,Tech meetups or events in your area,NaN,NaN,NaN,Straight / Heterosexual,NaN,Yes,Too short,Easy
72732,"I am not primarily a developer, but I write co...",No,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",NaN,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Contributed to open source software,...,A lot less welcome now than last year,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,Yes,Too long,Easy
78151,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Mexico,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,32.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,No,Appropriate in length,Easy
80200,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Netherlands,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,...,NaN,Tech articles written by other developers,25.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
52132,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Peru,No,Some college/university study without earning ...,I never declared a major,Completed an industry certification program (e...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,48.0,Man,NaN,NaN,Black or of African descent;East Asian;Hispani...,Yes,Appropriate in length,Easy
75561,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Singapore,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A humanities discipline (ex. literature, histo...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area,37.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
32250,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Switzerland,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken a part-time in-person course in programm...,...,Just as welcome now as I felt last year,Industry news about technologies you're intere...,30.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy

In [9]:
df.shape

(88883, 84)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 88883 entries, 63129 to 88816
Data columns (total 84 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MainBranch              88331 non-null  object
 1   Hobbyist                88883 non-null  object
 2   OpenSourcer             88883 non-null  object
 3   OpenSource              86842 non-null  object
 4   Employment              87181 non-null  object
 5   Country                 88751 non-null  object
 6   Student                 87014 non-null  object
 7   EdLevel                 86390 non-null  object
 8   UndergradMajor          75614 non-null  object
 9   EduOther                84260 non-null  object
 10  OrgSize                 71791 non-null  object
 11  DevType                 81335 non-null  object
 12  YearsCode               87938 non-null  object
 13  Age1stCode              87634 non-null  object
 14  YearsCodePro            74331 non-null  object
 15  CareerSat               72847 non-null  object
 16  JobSat                  70988 non-null  object
 17  MgrIdiot                61159 non-null  object
 18  MgrMoney                61157 non-null  object
 19  MgrWant                 61232 non-null  object
 20  JobSeek                 80555 non-null  object
 21  LastHireDate            79854 non-null  object
 22  LastInt                 67155 non-null  object
 23  FizzBuzz                71344 non-null  object
 24  JobFactors              79371 non-null  object
 25  ResumeUpdate            77877 non-null  object
 26  CurrencySymbol          71392 non-null  object
 27  CurrencyDesc            71392 non-null  object
 28  CompTotal               55945 non-null  float64
 29  CompFreq                63268 non-null  object
 30  ConvertedComp           55823 non-null  float64
 31  WorkWeekHrs             64503 non-null  float64
 32  WorkPlan                68914 non-null  object
 33  WorkChallenge           68141 non-null  object
 34  WorkRemote              70284 non-null  object
 35  WorkLoc                 70055 non-null  object
 36  ImpSyn                  71779 non-null  object
 37  CodeRev                 70390 non-null  object
 38  CodeRevHrs              49790 non-null  float64
 39  UnitTests               62668 non-null  object
 40  PurchaseHow             61108 non-null  object
 41  PurchaseWhat            62029 non-null  object
 42  LanguageWorkedWith      87569 non-null  object
 43  LanguageDesireNextYear  84088 non-null  object
 44  DatabaseWorkedWith      76026 non-null  object
 45  DatabaseDesireNextYear  69147 non-null  object
 46  PlatformWorkedWith      80714 non-null  object
 47  PlatformDesireNextYear  77443 non-null  object
 48  WebFrameWorkedWith      65022 non-null  object
 49  WebFrameDesireNextYear  62944 non-null  object
 50  MiscTechWorkedWith      59586 non-null  object
 51  MiscTechDesireNextYear  64511 non-null  object
 52  DevEnviron              87317 non-null  object
 53  OpSys                   87851 non-null  object
 54  Containers              85366 non-null  object
 55  BlockchainOrg           48175 non-null  object
 56  BlockchainIs            60165 non-null  object
 57  BetterLife              86269 non-null  object
 58  ITperson                87141 non-null  object
 59  OffOn                   86663 non-null  object
 60  SocialMedia             84437 non-null  object
 61  Extraversion            87305 non-null  object
 62  ScreenName              80486 non-null  object
 63  SOVisit1st              83877 non-null  object
 64  SOVisitFreq             88263 non-null  object
 65  SOVisitTo               88086 non-null  object
 66  SOFindAnswer            87816 non-null  object
 67  SOTimeSaved             86344 non-null  object
 68  SOHowMuchTime           68378 non-null  object
 69  SOAccount               87828 non-null  object
 70  SOPartFreq              74692 non-null  object
 71  SOJobs                  88066 non-null  object
 72  EntTeams                87841 non-null  object
 73  SOComm                  88131 non-null  object
 74  WelcomeChange           85855 non-null  object
 75  SONewContent            69560 non-null  object
 76  Age                     79210 non-null  float64
 77  Gender                  85406 non-null  object
 78  Trans                   83607 non-null  object
 79  Sexuality               76147 non-null  object
 80  Ethnicity               76668 non-null  object
 81  Dependents              83059 non-null  object
 82  SurveyLength            86984 non-null  object
 83  SurveyEase              87081 non-null  object
dtypes: float64(5), object(79)
memory usage: 59.7+ MB

In [11]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [85]:
schema_df = pd.read_csv("/Users/mac/Desktop/Pandas_Demo/data/survey_results_schema.csv", index_col='Column')

In [86]:
schema_df

                                                             QuestionText
Column
Respondent              Randomized respondent ID number (not in order ...
MainBranch              Which of the following options best describes ...
Hobbyist                                          Do you code as a hobby?
OpenSourcer                   How often do you contribute to open source?
OpenSource              How do you feel about the quality of open sour...
Employment              Which of the following best describes your cur...
Country                         In which country do you currently reside?
Student                 Are you currently enrolled in a formal, degree...
EdLevel                 Which of the following best describes the high...
UndergradMajor          What was your main or most important field of ...
EduOther                Which of the following types of non-degree edu...
OrgSize                 Approximately how many people are employed by ...
DevType                 Which of the following describe you? Please se...
YearsCode               Including any education, how many years have y...
Age1stCode              At what age did you write your first line of c...
YearsCodePro            How many years have you coded professionally (...
CareerSat               Overall, how satisfied are you with your caree...
JobSat                  How satisfied are you with your current job? (...
MgrIdiot                How confident are you that your manager knows ...
MgrMoney                Do you believe that you need to be a manager t...
MgrWant                 Do you want to become a manager yourself in th...
JobSeek                 Which of the following best describes your cur...
LastHireDate            When was the last time that you took a job wit...
LastInt                 In your most recent successful job interview (...
FizzBuzz                Have you ever been asked to solve FizzBuzz in ...
JobFactors              Imagine that you are deciding between two job ...
ResumeUpdate            Think back to the last time you updated your r...
CurrencySymbol          Which currency do you use day-to-day? If your ...
CurrencyDesc            Which currency do you use day-to-day? If your ...
CompTotal               What is your current total compensation (salar...
CompFreq                 Is that compensation weekly, monthly, or yearly?
ConvertedComp           Salary converted to annual USD salaries using ...
WorkWeekHrs              On average, how many hours per week do you work?
WorkPlan                          How structured or planned is your work?
WorkChallenge           Of these options, what are your greatest chall...
WorkRemote                                How often do you work remotely?
WorkLoc                                   Where would you prefer to work?
ImpSyn                  For the specific work you do, and the years of...
CodeRev                          Do you review code as part of your work?
CodeRevHrs              On average, how many hours per week do you spe...
UnitTests               Does your company regularly employ unit tests ...
PurchaseHow             How does your company make decisions about pur...
PurchaseWhat            What level of influence do you, personally, ha...
LanguageWorkedWith      Which of the following programming, scripting,...
LanguageDesireNextYear  Which of the following programming, scripting,...
DatabaseWorkedWith      Which of the following database environments h...
DatabaseDesireNextYear  Which of the following database environments h...
PlatformWorkedWith      Which of the following platforms have you done...
PlatformDesireNextYear  Which of the following platforms have you done...
WebFrameWorkedWith      Which of the following web frameworks have you...
WebFrameDesireNextYear  Which of the following web frameworks have you...
MiscTechWorkedWith      Which of the following other frameworks, libra...
MiscTechDesireNextYear  Which of the following other frameworks, libra...
DevEnviron              Which development environment(s) do you use re...
OpSys                   What is the primary operating system in which ...
Containers              How do you use containers (Docker, Open Contai...
BlockchainOrg           How is your organization thinking about or imp...
BlockchainIs            Blockchain / cryptocurrency technology is prim...
BetterLife              Do you think people born today will have a bet...
ITperson                 Are you the "IT support person" for your family?
OffOn                         Have you tried turning it off and on again?
SocialMedia                   What social media site do you use the most?
Extraversion              Do you prefer online chat or IRL conversations?
ScreenName                                           What do you call it?
SOVisit1st              To the best of your memory, when did you first...
SOVisitFreq             How frequently would you say you visit Stack O...
SOVisitTo               I visit Stack Overflow to... (check all that a...
SOFindAnswer            On average, how many times a week do you find ...
SOTimeSaved             Think back to the last time you solved a codin...
SOHowMuchTime           About how much time did you save? If you're no...
SOAccount                           Do you have a Stack Overflow account?
SOPartFreq              How frequently would you say you participate i...
SOJobs                  Have you ever used or visited Stack Overflow J...
EntTeams                Have you ever used Stack Overflow for Enterpri...
SOComm                  Do you consider yourself a member of the Stack...
WelcomeChange           Compared to last year, how welcome do you feel...
SONewContent            Would you like to see any of the following on ...
Age                     What is your age (in years)? If you prefer not...
Gender                  Which of the following do you currently identi...
Trans                                     Do you identify as transgender?
Sexuality               Which of the following do you currently identi...
Ethnicity               Which of the following do you identify as? Ple...
Dependents              Do you have any dependents (e.g., children, el...
SurveyLength            How do you feel about the length of the survey...
SurveyEase              How easy or difficult was this survey to compl...

In [87]:
schema_df.loc['SocialMedia']

QuestionText    What social media site do you use the most?
Name: SocialMedia, dtype: object

In [91]:
df['SocialMedia'].value_counts()

Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: SocialMedia, dtype: int64

In [92]:
df['Country'].value_counts()

United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: Country, Length: 179, dtype: int64

In [93]:
df.groupby(['Country'])

In [94]:
country_grp = df.groupby(['Country'])

In [95]:
country_grp.get_group('United States')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,Data or business analyst;Database administrato...,17,11,8,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Complete a take-home project;Interview with pe...,Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,90000.0,Yearly,90000.0,40.0,There is a schedule and/or spec (made by me or...,"Meetings;Non-work commitments (parenting, scho...",All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Rust...,Couchbase;DynamoDB;Firebase;MySQL,Firebase;MySQL;Redis,Android;AWS;Docker;IBM Cloud or Watson;iOS;Lin...,Android;AWS;Docker;IBM Cloud or Watson;Linux;S...,Angular/Angular.js;ASP.NET;Express;jQuery;Vue.js,Express;Vue.js,Node.js;Xamarin,Node.js;TensorFlow,Vim;Visual Studio;Visual Studio Code;Xcode,Windows,Development;Testing;Production,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,In real life (in person),Username,2011,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,NaN,Taken an online course in programming or softw...,"10,000 or more employees","Data or business analyst;Designer;Developer, b...",35,12,18,Slightly satisfied,Very dissatisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Financial perf...,I had a negative experience or interaction at ...,USD,United States dollar,103000.0,Yearly,103000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,"Less than half the time, but at least one day ...",Home,Average,No,NaN,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Elasticsearch;MySQL;Oracle;Redis,Elasticsearch;MySQL;Oracle;Redis,Docker;Linux;Raspberry Pi;Windows,Docker;Linux;Raspberry Pi;Windows,Angular/Angular.js;Ruby on Rails,Angular/Angular.js;Ruby on Rails,Node.js,Node.js,Sublime Text;Visual Studio;Visual Studio Code,Windows,"Outside of work, for personal projects",Not at all,NaN,Yes,Yes,Yes,Instagram,Online,Username,I don't remember,Daily or almost daily,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
23,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, full-stack",3,19,1,Slightly satisfied,Slightly satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,Opportunities for professional development;How...,I was preparing for a job search,USD,United States dollar,69000.0,Yearly,69000.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings;Non-work...,A few days each month,Office,Average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Pyth...,Bash/Shell/PowerShell;Go;HTML/CSS;Java;JavaScr...,Oracle;SQLite,Couchbase;DynamoDB;Elasticsearch;Firebase;Oracle,Docker;Google Cloud Platform,Docker;iOS;Slack,React.js;Ruby on Rails,Express;React.js;Ruby on Rails;Vue.js,NaN,React Native;TensorFlow,Visual Studio Code,MacOS,Development;Testing;Production,NaN,Useful for immutable record keeping outside of...,Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Multiple times per day,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,22.0,Man,No,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Easy
26,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","10,000 or more employees","Designer;Developer, back-end;Developer, deskto...",12,8,8,Very satisfied,Very satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles;Interview ...,No,Remote work options;Diversity of the company o...,I was preparing for a job search,USD,United States dollar,114000.0,Yearly,114000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,"Less than half the time, but at least one day ...",Home,Far above average,"Yes, because I see value in code review",2.0,"Yes, it's not part of our process but the deve...",Developers typically have the most influence o...,I have a great deal of influence,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...,C#;HTML/CSS;JavaScript;Objective-C;Ruby;SQL;Sw...,Microsoft SQL Server;MySQL;Redis;SQLite,Microsoft SQL Server;MySQL;Redis;SQLite,AWS;Docker;Linux;MacOS;Microsoft Azure;Windows...,Android;Docker;iOS;Linux;MacOS;Microsoft Azure...,Angular/Angular.js;ASP.NET;Drupal;Express;jQue...,Angular/Angular.js;ASP.NET,.NET;.NET Core;Node.js;Xamarin,.NET;.NET Core;Node.js,Notepad++;Sublime Text;Vim;Visual Studio;Xcode,MacOS,Development;Testing,Not at all,A passing fad,Yes,SIGH,Yes,I don't use social media,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,NaN,34.0,Man,No,Gay or Lesbian,NaN,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78292,NaN,No,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",United States,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","A health science (ex. nursing, pharmacy, radio...",Completed an industry certification program (e...,"Just me - I am a freelancer, sole proprietor, ...",Academic researcher,42,14,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;Python,Bash/Shell/PowerShell;C;Python,SQLite,SQLite,Linux;Raspberry Pi;Other(s):,Linux;Raspberry Pi;Other(s):,NaN,NaN,Chef,NaN,Emacs;IPython / Jupyter,Linux-based,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,Yes,Yes,I don't use social media,In real life (in person),NaN,2013,A few times per week,Find answers to specific questions,Less than once per week,The other resource was slightly faster,11-30 minutes,Not sure / can't remember,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Somewhat less welcome now than last year,NaN,60.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Neither easy nor difficult
82717,NaN,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,"Secondary school (e.g. American high school, G...",NaN,NaN,NaN,NaN,Less than 1 year,NaN,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android;Windows,Android;Microsoft Azure;Windows,NaN,NaN,NaN,NaN,NaN,MacOS,Testing,NaN,NaN,No,SIGH,Yes,Facebook,In real life (in person),Username,2018,Less than once per month or monthly,Find answers to specific questions,Less than once per week,NaN,60+ minutes,No,NaN,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...",Not sure,NaN,Industry news about technologies you're intere...,44.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Neither easy nor difficult
83397,NaN,Yes,Less than once per year,NaN,"Not employed, but looking for work",United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,12,9,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Python;SQL,C;C++;C#;Go;Java;JavaScript;Python;R;Ruby;SQL;...,NaN,NaN,Android;Arduino;Slack,Android;Arduino;Docker;iOS;Raspberry Pi;Slack,Flask,Django;Drupal;Flask;jQuery;React.js,NaN,Chef;Torch/PyTorch,Eclipse;IPython / Jupyter;Sublime Text,MacOS,I do not use containers,NaN,NaN,NaN,SIGH,Yes,NaN,NaN,Handle,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,They were about the same,NaN,Not sure / can't remember,NaN,Yes,"No, and I don't know what those are","No, not at all",Just as welcome now as I felt last year,NaN,27.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
85642,NaN,No,Less than once per year,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",United States,No,Associate degree,"Information systems, information technology, o...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...",Designer;Marketing or sales professional,20,7,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Go;HTML/CSS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visual Studio Code,Windows,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,SIGH,Yes,NaN,In real life (in person),Handle,2008,Less than once per month or monthly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not at all",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.0,"Non-binary, genderqueer, or gender non-conforming",NaN,Bisexual;Gay or Lesbian,White or of European descent,No,Appropriate in length,Easy
88282,NaN,Yes,Once a month or more often,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Developer, desktop or ente...",38,10,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;W...,Bash/Shell/PowerShell;C;Go;HTML/CSS;JavaScript...,NaN,NaN,Linux,Linux;Raspberry Pi,React.js,Vue.js,Node.js,Ansible,Vim,Linux-based,I do not use containers,NaN,An irresponsible use of resources,No,NaN,Yes,I don't use social media,In real life (in person),Username,I don't remember,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,NaN,No,Too short,Neither easy nor difficult

In [96]:
filt = df['Country'] == 'United States'
df.loc[filt]['SocialMedia'].value_counts()

Reddit                      5700
Twitter                     3468
Facebook                    2844
YouTube                     2463
I don't use social media    1851
Instagram                   1652
LinkedIn                    1020
WhatsApp                     609
Snapchat                     326
WeChat 微信                     93
VK ВКонта́кте                  9
Weibo 新浪微博                     8
Hello                          2
Youku Tudou 优酷                 1
Name: SocialMedia, dtype: int64

In [97]:
country_grp['SocialMedia'].value_counts()

Country      SocialMedia
Afghanistan  Facebook                    15
             YouTube                      9
             I don't use social media     6
             WhatsApp                     4
             Instagram                    1
                                         ..
Zimbabwe     Facebook                     3
             YouTube                      3
             Instagram                    2
             LinkedIn                     2
             Reddit                       1
Name: SocialMedia, Length: 1220, dtype: int64

In [98]:
country_grp['SocialMedia'].value_counts(normalize=True).loc['China']

SocialMedia
WeChat 微信                   0.670549
YouTube                     0.088186
Weibo 新浪微博                  0.069884
I don't use social media    0.044925
Twitter                     0.044925
Reddit                      0.019967
LinkedIn                    0.018303
Facebook                    0.013311
Instagram                   0.011647
Youku Tudou 优酷              0.011647
WhatsApp                    0.004992
VK ВКонта́кте               0.001664
Name: SocialMedia, dtype: float64

In [99]:
country_grp['ConvertedComp'].agg(['median', 'mean']).loc['Canada']

median     68705.000000
mean      134018.564909
Name: Canada, dtype: float64

In [100]:
filt = df['Country'] == 'India'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

3105

In [101]:
country_grp['LanguageWorkedWith'].apply(lambda x:x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [102]:
country_respondents = df['Country'].value_counts()
country_respondents

United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: Country, Length: 179, dtype: int64

In [105]:
country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x:x.str.contains('Python').sum())
country_uses_python

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [106]:
python_df = pd.concat([country_respondents, country_uses_python], axis='columns', sort=False)
python_df

                   Country  LanguageWorkedWith
United States        20949               10083
India                 9061                3105
Germany               5866                2451
United Kingdom        5737                2384
Canada                3395                1558
...                    ...                 ...
Tonga                    1                   0
Timor-Leste              1                   1
North Korea              1                   0
Brunei Darussalam        1                   0
Chad                     1                   0

[179 rows x 2 columns]

In [116]:
python_df.rename(columns={'Country': 'NumRespondents', 'LanguageWorkedWith': 'NumKnowsPython'}, inplace=True)

In [118]:
python_df

                   NumRespondents  NumKnowsPython
United States               20949           10083
India                        9061            3105
Germany                      5866            2451
United Kingdom               5737            2384
Canada                       3395            1558
...                           ...             ...
Tonga                           1               0
Timor-Leste                     1               1
North Korea                     1               0
Brunei Darussalam               1               0
Chad                            1               0

[179 rows x 2 columns]

In [120]:
python_df['PctKnowsPython'] = (python_df['NumKnowsPython']/python_df['NumKnowsPython'])

In [121]:
python_df['PctKnowsPython'] =  (python_df['NumKnowsPython']/python_df['NumRespondents']) * 100

In [122]:
python_df

                   NumRespondents  NumKnowsPython  PctKnowsPython
United States               20949           10083       48.131176
India                        9061            3105       34.267741
Germany                      5866            2451       41.783157
United Kingdom               5737            2384       41.554820
Canada                       3395            1558       45.891016
...                           ...             ...             ...
Tonga                           1               0        0.000000
Timor-Leste                     1               1      100.000000
North Korea                     1               0        0.000000
Brunei Darussalam               1               0        0.000000
Chad                            1               0        0.000000

[179 rows x 3 columns]

In [ ]:
python_df.sort_values(by='PctKnowsPython', ascending=False, inplace=True)

In [124]:
python_df.head(50)

                    NumRespondents  NumKnowsPython  PctKnowsPython
United States                20949           10083       48.131176
India                         9061            3105       34.267741
Germany                       5866            2451       41.783157
United Kingdom                5737            2384       41.554820
Canada                        3395            1558       45.891016
France                        2391            1054       44.081974
Brazil                        1948             767       39.373717
Poland                        1922             751       39.073881
Australia                     1903             790       41.513400
Netherlands                   1852             767       41.414687
Russian Federation            1694             708       41.794569
Spain                         1604             641       39.962594
Italy                         1576             625       39.657360
Sweden                        1274             496       38.932496
Switzerland                    978             460       47.034765
Israel                         952             457       48.004202
Turkey                         949             371       39.093783
Pakistan                       923             251       27.193933
Ukraine                        868             246       28.341014
Austria                        839             338       40.286055
Czech Republic                 764             285       37.303665
Romania                        760             253       33.289474
Iran                           738             268       36.314363
Belgium                        727             296       40.715268
China                          664             297       44.728916
Bulgaria                       659             181       27.465857
Mexico                         642             245       38.161994
South Africa                   627             202       32.216906
Denmark                        617             246       39.870340
Bangladesh                     605             204       33.719008
Norway                         574             232       40.418118
Greece                         556             226       40.647482
Argentina                      553             191       34.538879
Finland                        546             266       48.717949
Portugal                       525             182       34.666667
New Zealand                    524             236       45.038168
Nigeria                        522             152       29.118774
Hungary                        513             191       37.231969
Indonesia                      507             148       29.191321
Ireland                        501             209       41.716567
Serbia                         402             117       29.104478
Japan                          391             182       46.547315
Philippines                    381             117       30.708661
Sri Lanka                      372             137       36.827957
Egypt                          323             111       34.365325
Colombia                       313             108       34.504792
Singapore                      303             139       45.874587
Malaysia                       299              95       31.772575
Slovenia                       298             119       39.932886
Slovakia                       260             101       38.846154

In [125]:
python_df.loc['Japan']

NumRespondents    391.000000
NumKnowsPython    182.000000
PctKnowsPython     46.547315
Name: Japan, dtype: float64

In [26]:
schema_df.loc['MgrIdiot', 'QuestionText']

'How confident are you that your manager knows what they’re doing?'

In [27]:
schema_df.sort_index(inplace=True)

In [28]:
schema_df

                                                             QuestionText
Column
Age                     What is your age (in years)? If you prefer not...
Age1stCode              At what age did you write your first line of c...
BetterLife              Do you think people born today will have a bet...
BlockchainIs            Blockchain / cryptocurrency technology is prim...
BlockchainOrg           How is your organization thinking about or imp...
CareerSat               Overall, how satisfied are you with your caree...
CodeRev                          Do you review code as part of your work?
CodeRevHrs              On average, how many hours per week do you spe...
CompFreq                 Is that compensation weekly, monthly, or yearly?
CompTotal               What is your current total compensation (salar...
Containers              How do you use containers (Docker, Open Contai...
ConvertedComp           Salary converted to annual USD salaries using ...
Country                         In which country do you currently reside?
CurrencyDesc            Which currency do you use day-to-day? If your ...
CurrencySymbol          Which currency do you use day-to-day? If your ...
DatabaseDesireNextYear  Which of the following database environments h...
DatabaseWorkedWith      Which of the following database environments h...
Dependents              Do you have any dependents (e.g., children, el...
DevEnviron              Which development environment(s) do you use re...
DevType                 Which of the following describe you? Please se...
EdLevel                 Which of the following best describes the high...
EduOther                Which of the following types of non-degree edu...
Employment              Which of the following best describes your cur...
EntTeams                Have you ever used Stack Overflow for Enterpri...
Ethnicity               Which of the following do you identify as? Ple...
Extraversion              Do you prefer online chat or IRL conversations?
FizzBuzz                Have you ever been asked to solve FizzBuzz in ...
Gender                  Which of the following do you currently identi...
Hobbyist                                          Do you code as a hobby?
ITperson                 Are you the "IT support person" for your family?
ImpSyn                  For the specific work you do, and the years of...
JobFactors              Imagine that you are deciding between two job ...
JobSat                  How satisfied are you with your current job? (...
JobSeek                 Which of the following best describes your cur...
LanguageDesireNextYear  Which of the following programming, scripting,...
LanguageWorkedWith      Which of the following programming, scripting,...
LastHireDate            When was the last time that you took a job wit...
LastInt                 In your most recent successful job interview (...
MainBranch              Which of the following options best describes ...
MgrIdiot                How confident are you that your manager knows ...
MgrMoney                Do you believe that you need to be a manager t...
MgrWant                 Do you want to become a manager yourself in th...
MiscTechDesireNextYear  Which of the following other frameworks, libra...
MiscTechWorkedWith      Which of the following other frameworks, libra...
OffOn                         Have you tried turning it off and on again?
OpSys                   What is the primary operating system in which ...
OpenSource              How do you feel about the quality of open sour...
OpenSourcer                   How often do you contribute to open source?
OrgSize                 Approximately how many people are employed by ...
PlatformDesireNextYear  Which of the following platforms have you done...
PlatformWorkedWith      Which of the following platforms have you done...
PurchaseHow             How does your company make decisions about pur...
PurchaseWhat            What level of influence do you, personally, ha...
Respondent              Randomized respondent ID number (not in order ...
ResumeUpdate            Think back to the last time you updated your r...
SOAccount                           Do you have a Stack Overflow account?
SOComm                  Do you consider yourself a member of the Stack...
SOFindAnswer            On average, how many times a week do you find ...
SOHowMuchTime           About how much time did you save? If you're no...
SOJobs                  Have you ever used or visited Stack Overflow J...
SONewContent            Would you like to see any of the following on ...
SOPartFreq              How frequently would you say you participate i...
SOTimeSaved             Think back to the last time you solved a codin...
SOVisit1st              To the best of your memory, when did you first...
SOVisitFreq             How frequently would you say you visit Stack O...
SOVisitTo               I visit Stack Overflow to... (check all that a...
ScreenName                                           What do you call it?
Sexuality               Which of the following do you currently identi...
SocialMedia                   What social media site do you use the most?
Student                 Are you currently enrolled in a formal, degree...
SurveyEase              How easy or difficult was this survey to compl...
SurveyLength            How do you feel about the length of the survey...
Trans                                     Do you identify as transgender?
UndergradMajor          What was your main or most important field of ...
UnitTests               Does your company regularly employ unit tests ...
WebFrameDesireNextYear  Which of the following web frameworks have you...
WebFrameWorkedWith      Which of the following web frameworks have you...
WelcomeChange           Compared to last year, how welcome do you feel...
WorkChallenge           Of these options, what are your greatest chall...
WorkLoc                                   Where would you prefer to work?
WorkPlan                          How structured or planned is your work?
WorkRemote                                How often do you work remotely?
WorkWeekHrs              On average, how many hours per week do you work?
YearsCode               Including any education, how many years have y...
YearsCodePro            How many years have you coded professionally (...

In [29]:
person = {
    "first" : "Corey",
    "last" : "Schafer",
    "email" : "CoreyMSchafer@gmail.com"
}

In [30]:
people = {
    "first" : ["Corey"],
    "last" : ["Schafer"],
    "email" : ["CoreyMSchafer@gmail.com"]
}

In [31]:
people = {
    "first" : ["Corey", 'Jane', 'John', 'Adam'],
    "last" : ["Schafer", 'Doe', 'Doe', 'Doe'],
    "email" : ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com', 'A@email.com']
}

In [32]:
people['email']

['CoreyMSchafer@gmail.com',
 'JaneDoe@email.com',
 'JohnDoe@email.com',
 'A@email.com']

In [33]:
import pandas as pd

In [34]:
df =pd.DataFrame(people)

In [35]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe              A@email.com

In [36]:
df.sort_values(by=['last', 'first'],ascending=False)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
2   John      Doe        JohnDoe@email.com
1   Jane      Doe        JaneDoe@email.com
3   Adam      Doe              A@email.com

In [37]:
df.sort_values(by=['last', 'first'],ascending=[False, True])

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
3   Adam      Doe              A@email.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [38]:
df.sort_index()

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe              A@email.com

In [39]:
df['last'].sort_values

<bound method Series.sort_values of 0    Schafer
1        Doe
2        Doe
3        Doe
Name: last, dtype: object>

In [40]:
df['first'] + ' ' +df['last']

0    Corey Schafer
1         Jane Doe
2         John Doe
3         Adam Doe
dtype: object

In [41]:
df['full_name'] = df['first'] + ' ' + df['last']

In [42]:
df

   first     last                    email      full_name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe
3   Adam      Doe              A@email.com       Adam Doe

In [43]:
df.drop(columns=['first', 'last'], inplace=True)

In [44]:
df

                     email      full_name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe
3              A@email.com       Adam Doe

In [45]:
df['full_name'].str.split(' ', expand=True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe
3   Adam      Doe

In [46]:
df[['first', 'last']] = df['full_name'].str.split(' ', expand=True)

In [47]:
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3              A@email.com       Adam Doe   Adam      Doe

In [48]:
df.append({'first': 'Tony'}, ignore_index=True)

/var/folders/l_/cgp353n97qbfj4fhfsfw649c0000gn/T/ipykernel_2512/67547244.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append({'first': 'Tony'}, ignore_index=True)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3              A@email.com       Adam Doe   Adam      Doe
4                      NaN            NaN   Tony      NaN

In [49]:
people = {
    "first" : ['Tony', 'Steve'],
    "last" : ['stary', 'Rogers'],
    "email" : ['Iroman@avenge.com', 'JaneDoe@email.com']
}
df2 = pd.DataFrame(people)

In [50]:
df2

   first    last              email
0   Tony   stary  Iroman@avenge.com
1  Steve  Rogers  JaneDoe@email.com

In [51]:
df.append(df2, ignore_index=True, sort=False)

/var/folders/l_/cgp353n97qbfj4fhfsfw649c0000gn/T/ipykernel_2512/2503217469.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(df2, ignore_index=True, sort=False)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3              A@email.com       Adam Doe   Adam      Doe
4        Iroman@avenge.com            NaN   Tony    stary
5        JaneDoe@email.com            NaN  Steve   Rogers

In [52]:
df2

   first    last              email
0   Tony   stary  Iroman@avenge.com
1  Steve  Rogers  JaneDoe@email.com

In [53]:
df = df.append(df2, ignore_index=True, sort=False)

/var/folders/l_/cgp353n97qbfj4fhfsfw649c0000gn/T/ipykernel_2512/3370980109.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df2, ignore_index=True, sort=False)

In [54]:
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3              A@email.com       Adam Doe   Adam      Doe
4        Iroman@avenge.com            NaN   Tony    stary
5        JaneDoe@email.com            NaN  Steve   Rogers

In [55]:
df.append(df2, ignore_index=True, sort=False)

/var/folders/l_/cgp353n97qbfj4fhfsfw649c0000gn/T/ipykernel_2512/2503217469.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(df2, ignore_index=True, sort=False)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3              A@email.com       Adam Doe   Adam      Doe
4        Iroman@avenge.com            NaN   Tony    stary
5        JaneDoe@email.com            NaN  Steve   Rogers
6        Iroman@avenge.com            NaN   Tony    stary
7        JaneDoe@email.com            NaN  Steve   Rogers

In [56]:
df.drop(index=4)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3              A@email.com       Adam Doe   Adam      Doe
5        JaneDoe@email.com            NaN  Steve   Rogers

In [57]:
filt = df['last'] == 'Doe'
df.drop(index=df[df['last'] == 'Doe'].index)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
4        Iroman@avenge.com            NaN   Tony    stary
5        JaneDoe@email.com            NaN  Steve   Rogers

In [58]:
filt = (df['last'] == 'Schafer') | (df['first'] == 'John')

In [59]:
df[filt]

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
2        JohnDoe@email.com       John Doe   John      Doe

In [60]:
df.loc[-filt,'email']

1    JaneDoe@email.com
3          A@email.com
4    Iroman@avenge.com
5    JaneDoe@email.com
Name: email, dtype: object

In [61]:
df['email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
3                A@email.com
4          Iroman@avenge.com
5          JaneDoe@email.com
Name: email, dtype: object

In [62]:
type(df['email'])

pandas.core.series.Series

In [63]:
df.email

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
3                A@email.com
4          Iroman@avenge.com
5          JaneDoe@email.com
Name: email, dtype: object

In [64]:
df[['last','email']]

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com
2      Doe        JohnDoe@email.com
3      Doe              A@email.com
4    stary        Iroman@avenge.com
5   Rogers        JaneDoe@email.com

In [65]:
df.columns

Index(['email', 'full_name', 'first', 'last'], dtype='object')

In [66]:
df.iloc[0]

email        CoreyMSchafer@gmail.com
full_name              Corey Schafer
first                          Corey
last                         Schafer
Name: 0, dtype: object

In [67]:
df.iloc[:]

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3              A@email.com       Adam Doe   Adam      Doe
4        Iroman@avenge.com            NaN   Tony    stary
5        JaneDoe@email.com            NaN  Steve   Rogers

In [68]:
df.iloc[[0,1], 2]

0    Corey
1     Jane
Name: first, dtype: object

In [69]:
df.loc[[0,1],['email','last']]

                     email     last
0  CoreyMSchafer@gmail.com  Schafer
1        JaneDoe@email.com      Doe

In [70]:
df.shape

(6, 4)

In [71]:
df.columns

Index(['email', 'full_name', 'first', 'last'], dtype='object')

In [72]:
df['first']

0    Corey
1     Jane
2     John
3     Adam
4     Tony
5    Steve
Name: first, dtype: object

In [73]:
df.loc[0,'last']

'Schafer'

In [74]:
df.loc[0:2, 'first':'last']

   first     last
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [75]:
df.set_index('email')

                             full_name  first     last
email
CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
JaneDoe@email.com             Jane Doe   Jane      Doe
JohnDoe@email.com             John Doe   John      Doe
A@email.com                   Adam Doe   Adam      Doe
Iroman@avenge.com                  NaN   Tony    stary
JaneDoe@email.com                  NaN  Steve   Rogers

In [76]:
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3              A@email.com       Adam Doe   Adam      Doe
4        Iroman@avenge.com            NaN   Tony    stary
5        JaneDoe@email.com            NaN  Steve   Rogers

In [77]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [78]:
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3              A@email.com       Adam Doe   Adam      Doe
4        Iroman@avenge.com            NaN   Tony    stary
5        JaneDoe@email.com            NaN  Steve   Rogers

In [82]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [81]:
df.loc['CoreyMSchafer@gmail.com']

KeyError: 'CoreyMSchafer@gmail.com'

In [ ]:
df.set_index('email')

In [ ]:
df.index

In [ ]:
df.loc['CoreyMSchafer@gmail.com']

In [ ]:
df.iloc[0]

In [ ]:
df.reset_index(inplace=True)
df

In [ ]:
df['last'] == 'Doe'